language: java

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
    - jdk: openjdk8

install:
  - mvn dependency:go-offline

script:
  - mvn --offline test package

sudo: false
dist: trusty

notifications:
  email: false
